stages:
  - test
  - build
  - deploy

variables:
  SKIP_CODECOV: 1 # codecov is run on github actions, not necessary on gitlab build

book:
  stage: deploy
  tags:
    - linux
  script:
    - npm ci --no-audit
    - node release/book.js

generous:
  stage: deploy
  tags:
    - linux
  script:
    - npm ci --no-audit
    - node release/generous.js

test:linux:
  stage: test
  tags:
    - linux
  script:
    - npm ci --no-audit
    - node release/test.js

test:macos:
  stage: test
  tags:
    - darwin
  script:
    - npm ci --no-audit
    - node release/test.js

test:windows:
  stage: test
  tags:
    - windows
  script:
    - npm ci --no-audit
    - node release/test.js

build:linux:x86_64:
  stage: build
  tags:
    - linux
  script:
    - npm ci --no-audit
    - node release/build.js --os linux --arch x86_64
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts

build:darwin:x86_64:
  stage: build
  script:
    - npm ci --no-audit
    - node release/build.js --os darwin --arch x86_64
  tags:
    - darwin
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts

build:windows:i686:
  stage: build
  script:
    - npm ci --no-audit
    - node release/build.js --os windows --arch i686
  tags:
    - windows
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts

build:windows:x86_64:
  stage: build
  script:
    - npm ci --no-audit
    - node release/build.js --os windows --arch x86_64
  tags:
    - windows
  artifacts:
    expire_in: 1 week
    paths:
      - artifacts

deploy-itchio:
  stage: deploy
  tags:
    - linux
  script:
    - npm ci --no-audit
    - node release/deploy.js
